FROM python:3.12-slim-bookworm
WORKDIR /usr/src/app
COPY requirements.txt /usr/src/app
COPY ./samples/pydb_example.py /usr/src/app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 6899
CMD ["python", "pydb_example.py"]