FROM python:3.12-slim-bookworm
WORKDIR /usr/src/app
COPY . /usr/src/app
COPY docker-entrypoint.sh /entrypoint
ARG GIT_HASH
ENV GIT_HASH=${GIT_HASH:-dev}
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5678 8000
ENTRYPOINT ["/entrypoint"]